spring.application.name=ProyectoBoos
server.port=${PORT:8080}

# CONFIGURACIÓN PARA POSTGRESQL (NEON)
spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update
# Variables dinámicas (Se configuran en el panel de Render)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-sweet-thunder-atjbn5ry-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_SEtxbP5gCm1H}
# ==========================================
# SEGURIDAD (JWT)
# ==========================================
jwt.secret=ZzE2M3o4bDlweDZjcTR2NWI3YTlkMGVmaDJqM3M0dDVnNmg3ajhrOWwweDFjMnYz

# ==========================================
# CONFIGURACIÓN DE GOOGLE DRIVE (CARPETAS POR TIPO)
# ==========================================
google.drive.folder.excel=1LLvl84mx8h6SdjwPyGVgEq-Xfo_cs9mr
google.drive.folder.dwg=1I9VifqfhzkRqL5XISaIFIvQQ3IK6YrqN
google.drive.folder.docx=1C8usq7NxZM-9xw_Onvp_4dCz0-PcXumr


google.drive.folder.id=1LLvl84mx8h6SdjwPyGVgEq-Xfo_cs9mr


# ==========================================
# CREDENCIALES OAUTH 2.0 (REEMPLAZA A SERVICE ACCOUNT)
# ==========================================
google.drive.client.id=${GOOGLE_DRIVE_CLIENT_ID}
google.drive.client.secret=${GOOGLE_DRIVE_CLIENT_SECRET}
google.drive.refresh.token=${GOOGLE_DRIVE_REFRESH_TOKEN}
