spring.application.name=ProyectoBoos
server.port=${PORT:8080}

# CONFIGURACIÓN PARA POSTGRESQL (NEON)
spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update
# Variables dinámicas (Se configuran en el panel de Render)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-sweet-thunder-atjbn5ry-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_SEtxbP5gCm1H}
# ==========================================
# SEGURIDAD (JWT)
# ==========================================
jwt.secret=ZzE2M3o4bDlweDZjcTR2NWI3YTlkMGVmaDJqM3M0dDVnNmg3ajhrOWwweDFjMnYz
